// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutostartEnabled() {
  return window['go']['main']['App']['AutostartEnabled']();
}

export function BackgroundPaused() {
  return window['go']['main']['App']['BackgroundPaused']();
}

export function BrowseDataDir() {
  return window['go']['main']['App']['BrowseDataDir']();
}

export function CompleteOnboarding() {
  return window['go']['main']['App']['CompleteOnboarding']();
}

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function DataDir() {
  return window['go']['main']['App']['DataDir']();
}

export function EmbeddingsConfig() {
  return window['go']['main']['App']['EmbeddingsConfig']();
}

export function ExitApp() {
  return window['go']['main']['App']['ExitApp']();
}

export function GetMessage(arg1, arg2) {
  return window['go']['main']['App']['GetMessage'](arg1, arg2);
}

export function ListChats() {
  return window['go']['main']['App']['ListChats']();
}

export function MCPEndpoint() {
  return window['go']['main']['App']['MCPEndpoint']();
}

export function MCPPort() {
  return window['go']['main']['App']['MCPPort']();
}

export function OnboardingStatus() {
  return window['go']['main']['App']['OnboardingStatus']();
}

export function OpenInTelegram(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenInTelegram'](arg1, arg2, arg3);
}

export function PauseBackground() {
  return window['go']['main']['App']['PauseBackground']();
}

export function PurgeAll() {
  return window['go']['main']['App']['PurgeAll']();
}

export function PurgeChat(arg1) {
  return window['go']['main']['App']['PurgeChat'](arg1);
}

export function RebuildSemanticIndex() {
  return window['go']['main']['App']['RebuildSemanticIndex']();
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function ResumeBackground() {
  return window['go']['main']['App']['ResumeBackground']();
}

export function Search(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SetAutostartEnabled(arg1) {
  return window['go']['main']['App']['SetAutostartEnabled'](arg1);
}

export function SetChatPolicy(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetChatPolicy'](arg1, arg2, arg3, arg4, arg5);
}

export function SetDataDir(arg1) {
  return window['go']['main']['App']['SetDataDir'](arg1);
}

export function SetEmbeddingsConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetEmbeddingsConfig'](arg1, arg2, arg3, arg4);
}

export function SetMCPPort(arg1) {
  return window['go']['main']['App']['SetMCPPort'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function TelegramAuthStatus() {
  return window['go']['main']['App']['TelegramAuthStatus']();
}

export function TelegramChatFolders() {
  return window['go']['main']['App']['TelegramChatFolders']();
}

export function TelegramLoadChats() {
  return window['go']['main']['App']['TelegramLoadChats']();
}

export function TelegramRequestCode(arg1) {
  return window['go']['main']['App']['TelegramRequestCode'](arg1);
}

export function TelegramSetCredentials(arg1, arg2) {
  return window['go']['main']['App']['TelegramSetCredentials'](arg1, arg2);
}

export function TelegramSignIn(arg1, arg2) {
  return window['go']['main']['App']['TelegramSignIn'](arg1, arg2);
}

export function ToggleMCP(arg1) {
  return window['go']['main']['App']['ToggleMCP'](arg1);
}

export function TrayStatus() {
  return window['go']['main']['App']['TrayStatus']();
}
