// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AutostartEnabled():Promise<boolean>;

export function BackgroundPaused():Promise<boolean>;

export function BrowseDataDir():Promise<string>;

export function CompleteOnboarding():Promise<domain.OnboardingStatus>;

export function CreateBackup(arg1:string):Promise<string>;

export function DataDir():Promise<string>;

export function EmbeddingsConfig():Promise<domain.EmbeddingsConfig>;

export function EmbeddingsProgress():Promise<domain.EmbeddingsProgress>;

export function ExitApp():Promise<void>;

export function GetMessage(arg1:number,arg2:number):Promise<domain.Message>;

export function ListChats():Promise<Array<domain.ChatPolicy>>;

export function MCPEndpoint():Promise<string>;

export function MCPPort():Promise<number>;

export function OnboardingStatus():Promise<domain.OnboardingStatus>;

export function OpenInTelegram(arg1:number,arg2:number,arg3:string):Promise<string>;

export function PauseBackground():Promise<domain.IndexStatus>;

export function PurgeAll():Promise<domain.IndexStatus>;

export function PurgeChat(arg1:number):Promise<domain.IndexStatus>;

export function RebuildSemanticIndex():Promise<string>;

export function RestoreBackup(arg1:string):Promise<string>;

export function ResumeBackground():Promise<domain.IndexStatus>;

export function Search(arg1:string,arg2:string,arg3:boolean,arg4:Array<number>,arg5:number,arg6:number,arg7:number):Promise<Array<domain.SearchResult>>;

export function SetAutostartEnabled(arg1:boolean):Promise<boolean>;

export function SetChatPolicy(arg1:number,arg2:boolean,arg3:string,arg4:boolean,arg5:string):Promise<void>;

export function SetDataDir(arg1:string):Promise<string>;

export function SetEmbeddingsConfig(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SetMCPPort(arg1:number):Promise<domain.IndexStatus>;

export function Status():Promise<domain.IndexStatus>;

export function SyncNow():Promise<domain.IndexStatus>;

export function TelegramAuthStatus():Promise<domain.TelegramAuthStatus>;

export function TelegramChatFolders():Promise<Array<domain.ChatFolder>>;

export function TelegramLoadChats():Promise<Array<domain.ChatPolicy>>;

export function TelegramRequestCode(arg1:string):Promise<domain.TelegramAuthStatus>;

export function TelegramSetCredentials(arg1:number,arg2:string):Promise<void>;

export function TelegramSignIn(arg1:string,arg2:string):Promise<domain.TelegramAuthStatus>;

export function TestEmbeddings():Promise<domain.EmbeddingsTestResult>;

export function ToggleMCP(arg1:boolean):Promise<void>;

export function TrayStatus():Promise<string>;
